[package]
name = "qment"
version = "0.1.0"
edition = "2021"

[dependencies]
# Ui
eframe = "0.19.0"

# Serialisation
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "*"

# File Handling
rfd = "0.10.0"

# Datatypes
indexmap = { version = "1.9.2", features = ["serde"] }